C
C---   INCLUDE-BLOCK SHELLS   ------------------------------------------
C
      COMMON /SHELLS/ XJ(JSMXMX),XL(JSMXMX),XKAPPA(JSMXMX),
     *                PHASFC(JSMXMX),GPARIT(JSMXMX),
     *                DELPIN,DELNIN,
     *                NPROT,NNEUT,NSHLPR,NSHLNE,
     *                APROT,ANEUT,ABARY,NSHLTO,
     *                NPDD,NNDD,NSHLDT,
     *                IFPAIR(2),JSMAX(2),NSMAX(JSMXMX,2),
     *                NPLACE(NMAXMX,JSMXMX,2)
