C
C---   INCLUDE-BLOCK  WAVEFN   -----------------------------------------
C
      COMMON/WAVEFN/SPENRG(NSHLMX),WEIGHT(NSHLMX),XMULT(NSHLMX),
     *              SRHO(NGRDMX),VRHO(NGRDMX),DRHO(NGRDMX),
     *              RRHO(NGRDMX),CRHO(NGRDMX),TERHO(NGRDMX),
     *              SMESON(NGRDMX),VMESON(NGRDMX),DMESON(NGRDMX),
     *              RMESON(NGRDMX),
     *              SPOT(NGRDMX),VPOT(NGRDMX),DPOT(NGRDMX),
     *              RPOT(NGRDMX),COULPT(NGRDMX),D1VPOT(NGRDMX),
     *              WFN(NGRDMS)
