C
C---   INCLUDE-BLOCK  YLAMDA   -----------------------------------------
C
      COMMON/YLAMDA/YMSL(800),YDMQL(800),YDMSL(800),
     *              SMESCPDL(NGRDMX),SMESCPL,VMESCPL,VMESTCL,
     *              SPOTML(NGRDMX),SPOTDL(NGRDMX),VPOTL(NGRDMX),
     *              D1VPOTL(NGRDMX),D2VPOTL(NGRDMX),              
     *              SRHOL(NGRDMX),VRHOL(NGRDMX),TERHOL(NGRDMX),
     *              CRHOL(NGRDMX),
     *              WFNL(NGRDMX),SPENRGL,RGW(NUCLMX)
 